# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: 'en'

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{Kernel.php}'

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    ## AMQP
    ##########
    PhpAmqpLib\Connection\AMQPStreamConnection:
        arguments:
            $host: '%env(CLOUDAMQP_HOST)%'
            $port: '%env(CLOUDAMQP_PORT)%'
            $user: '%env(CLOUDAMQP_USER)%'
            $password: '%env(CLOUDAMQP_PASS)%'
            $vhost: '%env(CLOUDAMQP_VHOST)%'

    ## AMQP Declarer
    ##########
    App\Producer\Infrastructure\Messenger\AMQP\Declarer\QueueDeclarer:
        arguments:
            $passive: false
            $durable: false
            $exclusive: false
            $autoDelete: false

    App\Producer\Infrastructure\Messenger\AMQP\Declarer\ExchangeDeclarer:
        arguments:
            $exchangeType: 'direct'
            $passive: false
            $durable: false
            $autoDelete: false

    ## AMQP Factory
    ##########
    App\Producer\Infrastructure\Messenger\AMQP\Factory\QueueFactory:
        arguments:
            $maxMessagesPerQueue: '%env(MAX_MSG_QUEUE)%'

    App\Producer\Infrastructure\Messenger\AMQP\Factory\MessageFactory:
        arguments:
            $contentType: 'text/plain'
            $deliveryMode: 2


    ## CLI
    ##########
    App\Producer\Infrastructure\Ui\CLI\SetupChannel:
        arguments:
            $channelManager: '@App\Producer\Infrastructure\Messenger\AMQP\ChannelManager'
            $queueDeclarer: '@App\Producer\Infrastructure\Messenger\AMQP\Declarer\QueueDeclarer'
            $queueFactory: '@App\Producer\Infrastructure\Messenger\AMQP\Factory\QueueFactory'
            $exchangeDeclarer: '@App\Producer\Infrastructure\Messenger\AMQP\Declarer\ExchangeDeclarer'
            $exchangeName: '%env(EXCHANGE)%'

    App\Producer\Infrastructure\Ui\CLI\SendMessages:
        arguments:
            $channelManager: '@App\Producer\Infrastructure\Messenger\AMQP\ChannelManager'
            $messageFactory: '@App\Producer\Infrastructure\Messenger\AMQP\Factory\MessageFactory'
            $settingsReader: '@App\Producer\Infrastructure\Storage\Settings\SettingsReader'
            $exchangeName: '%env(EXCHANGE)%'
            $messagesBatchSize: '%env(MSG_BATCH_AMOUNT)%'
